package com.platform.advertising;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.platform.advertising.Occupation;

import com.platform.advertising.OccupationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig occupationDaoConfig;

    private final OccupationDao occupationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        occupationDaoConfig = daoConfigMap.get(OccupationDao.class).clone();
        occupationDaoConfig.initIdentityScope(type);

        occupationDao = new OccupationDao(occupationDaoConfig, this);

        registerDao(Occupation.class, occupationDao);
    }
    
    public void clear() {
        occupationDaoConfig.getIdentityScope().clear();
    }

    public OccupationDao getOccupationDao() {
        return occupationDao;
    }

}
