package com.platform.advertising;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OCCUPATION.
 */
public class Occupation {

    private Long id;
    private String idStr;
    private String createTime;
    private String updateTime;
    private String sort;
    private String name;
    private String value;
    private String jp;
    private String qp;
    private String remark;

    public Occupation() {
    }

    public Occupation(Long id) {
        this.id = id;
    }

    public Occupation(Long id, String idStr, String createTime, String updateTime, String sort, String name, String value, String jp, String qp, String remark) {
        this.id = id;
        this.idStr = idStr;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.sort = sort;
        this.name = name;
        this.value = value;
        this.jp = jp;
        this.qp = qp;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdStr() {
        return idStr;
    }

    public void setIdStr(String idStr) {
        this.idStr = idStr;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public String getSort() {
        return sort;
    }

    public void setSort(String sort) {
        this.sort = sort;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getJp() {
        return jp;
    }

    public void setJp(String jp) {
        this.jp = jp;
    }

    public String getQp() {
        return qp;
    }

    public void setQp(String qp) {
        this.qp = qp;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
