package com.platform.advertising;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.platform.advertising.UserInfo;
import com.platform.advertising.Occupation;
import com.platform.advertising.Age;

import com.platform.advertising.UserInfoDao;
import com.platform.advertising.OccupationDao;
import com.platform.advertising.AgeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig occupationDaoConfig;
    private final DaoConfig ageDaoConfig;

    private final UserInfoDao userInfoDao;
    private final OccupationDao occupationDao;
    private final AgeDao ageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        occupationDaoConfig = daoConfigMap.get(OccupationDao.class).clone();
        occupationDaoConfig.initIdentityScope(type);

        ageDaoConfig = daoConfigMap.get(AgeDao.class).clone();
        ageDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        occupationDao = new OccupationDao(occupationDaoConfig, this);
        ageDao = new AgeDao(ageDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(Occupation.class, occupationDao);
        registerDao(Age.class, ageDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        occupationDaoConfig.getIdentityScope().clear();
        ageDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public OccupationDao getOccupationDao() {
        return occupationDao;
    }

    public AgeDao getAgeDao() {
        return ageDao;
    }

}
